### ISSUE TITLE
请问，ACDD支持android 2.3 及以上版本吗？如果对android版本有要求，目前有发现什么绕不开的限制吗？

### ISSUE THREAD

**Issue by DavidYes** [bunnyblue/ACDDExtension#39]
我看ACDDCore要求  android:minSdkVersion="14"。

**Comment by bunnyblue** [comment]
对。以前支持。后来为了支持stub模式，去掉了，3.0不支持。估计也没人用。
2.3的版本跑这个体验太差了，不打算继续支持了，2.3支持，但是被屏蔽了，下版本干掉这部分代码

**Comment by DavidYes** [comment]
2.3的能继续保持支持状态吗？可以提供选择而已。估计明年android都是4.0的起步再干掉这部分代码不迟。
另外，插件so的动态加载，是否可以支持 主宿app启动后，远程联网从服务器端下载qrcode.so，然后下载完成后加载，或者在需要启动qrcode的时候再加载？如果可以支持怎么做呢？我看手机上的/data/data下面的app包里面的文件都放到 \files\storage 目录了，且不是.so文件了。

**Comment by bunnyblue** [comment]
2.3的在上面还。
可以联网下载啊，都预留接口了，自己实现就好了。ACDD 里面有install方法，那个so本来就是apk啊，只是为了加快启动速度这样搞的

**Comment by DavidYes** [comment]
奇怪，我看 root@C15:/data/data/org.acdd.launcher/lib # 目录是有.so文件的。可能是我这边的问题。

**Comment by bunnyblue** [comment]
这个so是zip文件，改为so放lib里面，安装apk的时候会插件解压到本地，然后引擎用的时候可以直接使用了，实际上是apk，里面就是so，这个没问题，storage里面是odex或者oat

**Comment by DavidYes** [comment]
我是了用例代码
else if (id==R.id.action_updateQR){
            File file=new File("/sdcard/app-debug.apk");
            if (!file.exists()){

                Toast.makeText(MainActivity.this, "QRCode Update  pkg not exist", Toast.LENGTH_SHORT).show();
            }
            try {
                ACDD.getInstance().updateBundle("com.acdd.qrcode",file);
            } catch (BundleException e) {
                e.printStackTrace();
            }
        }

新生成的 app-debug.apk将mainactivity修改了一下layout界面字符串， 看上去无法动态更新qrcode，即使重启也无法更新qrcode。

请问 主宿apk未集成qrcode然后动态加载，或者主宿集成qrcode后动态更新 是否有实现?

**Comment by bunnyblue** [comment]
你的原来的qrcode是com.acdd.qrcode?这个以前测试了，等周末我看下吧，编译工具的问题这儿提，framework相关的到主项目提好了

**Comment by DavidYes** [comment]
好的，能否将 安装，更新，卸载 整套流程 一起完善下？

**Comment by bunnyblue** [comment]
提交了已经，你看下，刚才那个因为home里面包名写错了，导致升级失败

**Comment by DavidYes** [comment]
好的，Thanks.

**Comment by bunnyblue** [comment]
demo里面写的不是很完善，升级失败的话有异常输出的,刚才那个问题包名是 update传入的包名是com 不在返回内，已经把异常抛出了。在home那个项目有打印异常，只不过没在解码显示

**Comment by DavidYes** [comment]
测试了，还是不能动态更新。而且之前正常的DEMO，打开QRCode的时候，logcat会输出厦门的异常；
11-19 20:04:00.911 8461-8461/org.acdd.launcher E/ActionBarView: Activity component name not found!
                                                                android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{org.acdd.launcher/com.acdd.qrcode.MainActivity}
                                                                    at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:232)
                                                                    at android.app.ApplicationPackageManager.getActivityIcon(ApplicationPackageManager.java:707)
                                                                    at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:209)
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2832)
                                                                    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2896)
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270)
                                                                    at android.app.Activity.setContentView(Activity.java:1881)
                                                                    at com.acdd.qrcode.MainActivity.onCreate(MainActivity.java:56)
                                                                    at android.app.Activity.performCreate(Activity.java:5122)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
                                                                    at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:523)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:165)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                    at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5391)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by bunnyblue** [comment]
出了问题看些请看下堆栈，这个直接运行也会异常好吧
```
setContentView(OGSdkResUtil.getResofR(this).getLayout("activity_main"));
```
安装了更新需要重启app
