### ISSUE TITLE
Build不成功

### ISSUE THREAD

**Issue by gxmdboy** [bunnyblue/ACDDExtension#52]
系统：win 10
AS版本：2.1.3
Gradle版本：2.1.3
工程刚下未改动
直接将Sample导入到Android Studio里面

所有的模块都不能build成功
Information:Gradle tasks [:HomeLauncher:clean, :HomeLauncher:generateAcddDebugSources, :HomeLauncher:prepareAcddDebugUnitTestDependencies, :HomeLauncher:mockableAndroidJar, :HomeLauncher:generateAcddDebugAndroidTestSources, :HomeLauncher:assembleAcddDebug]
:HomeLauncher:clean
:HomeLauncher:preBuild UP-TO-DATE
:HomeLauncher:preAcddDebugBuild UP-TO-DATE
:HomeLauncher:checkAcddDebugManifest
:HomeLauncher:prepareAcddDebugDependencies
:HomeLauncher:compileAcddDebugAidl
:HomeLauncher:compileAcddDebugRenderscript
:HomeLauncher:generateAcddDebugBuildConfig
:HomeLauncher:mergeAcddDebugShaders
:HomeLauncher:compileAcddDebugShaders
:HomeLauncher:generateAcddDebugAssets
:HomeLauncher:mergeAcddDebugAssets
:HomeLauncher:generateAcddDebugResValues UP-TO-DATE
:HomeLauncher:generateAcddDebugResources
:HomeLauncher:mergeAcddDebugResources
:HomeLauncher:processAcddDebugManifest
:HomeLauncher:processAcddDebugResources FAILED
Error:Execution failed for task ':HomeLauncher:processAcddDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Users\ucmed\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 1.104 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

几乎都是这种错误

**Comment by gxmdboy** [comment]
我替换了aapt.exe文件，build可以了
直接跑这些插件apk不行么，点了run报错
```
FATAL EXCEPTION: main
                                                                       Process: com.acdd.homelauncher, PID: 15176
                                                                       java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.acdd.homelauncher/com.acdd.homelauncher.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.acdd.homelauncher.MainActivity" on path: DexPathList[[zip file "/data/app/com.acdd.homelauncher-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2236)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.acdd.homelauncher.MainActivity" on path: DexPathList[[zip file "/data/app/com.acdd.homelauncher-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.acdd.homelauncher.MainActivity" on path: DexPathList[[dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.acdd.homelauncher/files/instant-run/dex/slice-slice_0-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                                           at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 13 more
                                                                       		Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
                                                                           at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                           at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                           at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                           at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                           			... 17 more
```

**Comment by bunnyblue** [comment]
默认这个包不能直接运行，缺少类，你应该取出output apks下面有个acdd的包，把这个包取出来放在launcher里面，具体你看下wiki里面
