### ISSUE TITLE
替换buildTools23.0.2，插件项目可以正常编译安装，唯独HomeLauncher编译安装后报错闪退？大神，是我编译的问题吗？

### ISSUE THREAD

**Issue by chunca** [bunnyblue/ACDDExtension#7]
Process: com.acdd.homelauncher, PID: 14366
                                                                       java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.acdd.homelauncher/com.acdd.homelauncher.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.acdd.homelauncher.MainActivity" on path: DexPathList[[zip file "/data/app/com.acdd.homelauncher-1/base.apk"],nativeLibraryDirectories=[/data/app/com.acdd.homelauncher-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                           at android.os.Looper.loop(Looper.java:207)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5968)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.acdd.homelauncher.MainActivity" on path: DexPathList[[zip file "/data/app/com.acdd.homelauncher-1/base.apk"],nativeLibraryDirectories=[/data/app/com.acdd.homelauncher-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                           at android.os.Looper.loop(Looper.java:207) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5968) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800) 
                                                                       	Suppressed: java.lang.NoClassDefFoundError: com.acdd.homelauncher.MainActivity
                                                                           at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                           at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                           at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                           at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                           		... 13 more
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.acdd.homelauncher.MainActivity
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 12 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by bunnyblue** [comment]
plz paste android version、plugin version

**Comment by bunnyblue** [comment]
you just run  HomeLauncher,or run in ACDD?

**Comment by chunca** [comment]
抱歉，这么回复！手机是小米4，android版本6.0.1
直接运行 HomeLauncher，安装到手机，点击图标后就直接崩掉了

**Comment by bunnyblue** [comment]
No,you must put apk to acdd lib/arm
